### External Libraries

* Third-party libraries: set of pre-written codes to perform tasks like data analysis, building models etc.
* Example: import numpy as np

1. Data Analysis: Numpy, Pandas, Matplotlib, Seaborn
2. Machine Learning / Deep Learning: sklearn, Tensorflow, Pytorch
3. Web Development: Django, Flask
4. Web-Scraping: requests, beautifulsoup4
5. Scientific Computing: Scipy,Sympy
6. Computer Vision: OpenCV


###### pip install pandas

# Numpy Array

In [1]:
#importing numpy library
import numpy as np

In [2]:
#1. Vectors: 1D arrays
#2. Matrices: 2D arrays

In [3]:
my_lst = [1,2,3,4]
my_array = np.array(my_lst)

In [5]:
type(my_array)

numpy.ndarray

In [6]:
my_array

array([1, 2, 3, 4])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Built-In Methods

In [10]:
#arange: evenly spaced values within a given interval
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(2,28,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26])

In [13]:
#zeros
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
#ones
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
#linspace: returns evenly spaced numbers over a specified interval
np.linspace(0,8)

array([0.        , 0.16326531, 0.32653061, 0.48979592, 0.65306122,
       0.81632653, 0.97959184, 1.14285714, 1.30612245, 1.46938776,
       1.63265306, 1.79591837, 1.95918367, 2.12244898, 2.28571429,
       2.44897959, 2.6122449 , 2.7755102 , 2.93877551, 3.10204082,
       3.26530612, 3.42857143, 3.59183673, 3.75510204, 3.91836735,
       4.08163265, 4.24489796, 4.40816327, 4.57142857, 4.73469388,
       4.89795918, 5.06122449, 5.2244898 , 5.3877551 , 5.55102041,
       5.71428571, 5.87755102, 6.04081633, 6.20408163, 6.36734694,
       6.53061224, 6.69387755, 6.85714286, 7.02040816, 7.18367347,
       7.34693878, 7.51020408, 7.67346939, 7.83673469, 8.        ])

In [19]:
0.84210526-0.42105263

0.42105263

In [20]:
1.26315789-0.84210526

0.42105263000000004

In [23]:
#eye: identity Matrix
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Random

In [24]:
#rand: random samples from a uniform distribution over [0,1)
np.random.rand(8)

array([0.61539285, 0.58995572, 0.55388944, 0.78030682, 0.45336219,
       0.61895548, 0.07996621, 0.91988374])

In [26]:
np.random.rand(5,5)

array([[0.59167149, 0.57022654, 0.0336666 , 0.38213581, 0.92868629],
       [0.30975876, 0.24845114, 0.19429907, 0.59620341, 0.65382596],
       [0.52485897, 0.62287402, 0.90883229, 0.1019447 , 0.78124693],
       [0.54489409, 0.45653181, 0.12906252, 0.41420287, 0.98533647],
       [0.34039466, 0.29784662, 0.01158967, 0.44820077, 0.22561789]])

In [27]:
#randn: random samples from standard normal distribution (sigma = 1)

np.random.randn(12)

array([ 0.97710768, -1.13043104, -1.76048978, -0.76652124,  0.37228809,
       -0.01048105,  1.2691254 , -1.25942855,  1.29717784, -0.87007796,
       -0.22735055, -1.26199782])

In [28]:
np.random.randn(7,2)

array([[ 0.08888616,  0.14798258],
       [-0.57903726, -2.27152889],
       [-0.14605832, -0.35819806],
       [ 0.97465669,  2.56426579],
       [-0.53214341,  1.12015823],
       [-0.74024337, -1.36554621],
       [ 0.34874321,  0.74390011]])

In [35]:
#randint: return random integers from low(included) to high(excluded)

np.random.randint(1,100)

66

In [40]:
np.random.randint(1,100,15)

array([ 4, 73, 12, 39, 54, 36, 34, 60, 94, 88,  8, 77, 39, 92, 87])

In [54]:
np.random.randint(1,100,(3,5))

array([[57, 39, 83,  2, 31],
       [39, 31, 74, 91, 47],
       [48, 90, 94, 60, 85]])

In [64]:
#seed: sets random state (produce same random results again and again)
np.random.seed(91)
np.random.randint(1,100,(3,5))

array([[51, 47, 83, 94, 30],
       [37,  3, 29, 43, 15],
       [29, 18, 18, 89, 66]])

In [70]:
np.random.seed(91)
np.random.randn(5,4)

array([[-0.60612102, -1.05993975, -0.55091967, -0.27568627],
       [ 1.22225373, -0.90585899,  0.06935217,  2.17865566],
       [ 0.14731691,  0.51725713, -1.29397945, -1.0548876 ],
       [ 0.46476874,  0.23410601,  1.77886602,  0.86387667],
       [-0.02505936, -0.15748755, -0.69803799, -0.17109056]])

### Array Attributes and Methods

In [75]:
arr = np.arange(32)
ranarr = np.random.randint(0,50,10)

In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [77]:
ranarr

array([47, 17, 10, 22,  0,  2, 39, 28, 29, 32])

In [79]:
#reshape: contains same data with a new shape
arr.reshape(4,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [80]:
arr.reshape(2,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [82]:
#shape
arr.shape

(32,)

In [84]:
arr_new = arr.reshape(1,32)

In [85]:
arr_new.shape

(1, 32)

In [87]:
arr_new1 = arr.reshape(32,1)
arr_new1.shape

(32, 1)

In [88]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [89]:
arr_new

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [90]:
arr_new1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31]])

In [94]:

demo_ar = np.random.randint(1,100,15)
demo_ar

array([58, 71, 62, 59, 94,  2, 86, 10, 11,  2,  8, 18, 19,  9, 95])

In [95]:
demo_ar.max()

95

In [96]:
demo_ar.argmax()

14

In [97]:
demo_ar.min()

2

In [98]:
demo_ar.argmin()

5

# Numpy Indexing and Selection

In [101]:
arr = np.arange(1,31,4)
arr

array([ 1,  5,  9, 13, 17, 21, 25, 29])

In [102]:
arr[3]

13

In [103]:
arr[1:4]

array([ 5,  9, 13])

# Broadcasting

In [107]:
arr[0:3] = 100
arr

array([100, 100, 100,  13,  17,  21,  25,  29])

In [114]:
#reset
arr = np.arange(11,51,4)
arr

array([11, 15, 19, 23, 27, 31, 35, 39, 43, 47])

In [115]:
slice_of_arr = arr[0:3]
slice_of_arr

array([11, 15, 19])

In [116]:
slice_of_arr[0:3] = 100
slice_of_arr

array([100, 100, 100])

In [117]:
arr

array([100, 100, 100,  23,  27,  31,  35,  39,  43,  47])

Data is not copied, it is just a view of original array. This avoids memory problems.

In [118]:
arr = np.arange(11,51,4)
arr

array([11, 15, 19, 23, 27, 31, 35, 39, 43, 47])

In [119]:
arr_copy = arr.copy()

In [121]:
slice_of_arr = arr_copy[0:3]
slice_of_arr[:]=100

In [122]:
slice_of_arr

array([100, 100, 100])

In [123]:
arr_copy

array([100, 100, 100,  23,  27,  31,  35,  39,  43,  47])

In [124]:
arr

array([11, 15, 19, 23, 27, 31, 35, 39, 43, 47])

### Indexing a 2D array (Matrices)


In [127]:
arr_2d = np.array([[11,12,13],[14,15,16],[17,18,19]])
arr_2d

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [129]:
arr_2d[0][1]

12

In [130]:
arr_2d[0,1]

12

In [131]:
arr_2d[:,1]

array([12, 15, 18])

In [134]:
arr_new_2d = np.random.randint(1,100,(3,5))
arr_new_2d

array([[ 6, 30, 41, 35, 61],
       [37, 55, 42, 37,  7],
       [43, 20, 47, 42, 23]])

In [136]:
arr_new_2d[1:,-2:]

array([[37,  7],
       [42, 23]])

In [139]:
arr_new_2d[:2,2:4]

array([[41, 35],
       [42, 37]])

In [141]:
np.random.seed(91)
arr_new_2d = np.random.randint(1,100,(6,5))
arr_new_2d

array([[51, 47, 83, 94, 30],
       [37,  3, 29, 43, 15],
       [29, 18, 18, 89, 66],
       [19, 21, 41, 87, 94],
       [21, 18, 44, 71, 52],
       [15, 69, 62, 35, 79]])

18,18,89
21,41,87

In [143]:
arr_new_2d[2:4,1:4]

array([[18, 18, 89],
       [21, 41, 87]])

### Conditional Selection

In [144]:
arr = np.arange(1,51,4)
arr

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

In [146]:
arr[arr > 21]

array([25, 29, 33, 37, 41, 45, 49])

# Numpy Operations

In [148]:
arr + arr

array([ 2, 10, 18, 26, 34, 42, 50, 58, 66, 74, 82, 90, 98])

In [149]:
arr*arr

array([   1,   25,   81,  169,  289,  441,  625,  841, 1089, 1369, 1681,
       2025, 2401])

In [150]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [151]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Universal Array Functions

In [152]:
arr

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

In [153]:
np.sqrt(arr)

array([1.        , 2.23606798, 3.        , 3.60555128, 4.12310563,
       4.58257569, 5.        , 5.38516481, 5.74456265, 6.08276253,
       6.40312424, 6.70820393, 7.        ])

In [154]:
np.exp(arr)

array([2.71828183e+00, 1.48413159e+02, 8.10308393e+03, 4.42413392e+05,
       2.41549528e+07, 1.31881573e+09, 7.20048993e+10, 3.93133430e+12,
       2.14643580e+14, 1.17191424e+16, 6.39843494e+17, 3.49342711e+19,
       1.90734657e+21])

In [155]:
np.sin(arr)

array([ 0.84147098, -0.95892427,  0.41211849,  0.42016704, -0.96139749,
        0.83665564, -0.13235175, -0.66363388,  0.99991186, -0.64353813,
       -0.15862267,  0.85090352, -0.95375265])

In [156]:
np.log(arr)

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207, 3.80666249, 3.8918203 ])

In [157]:
arr

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

In [158]:
arr.sum()

325

In [159]:
arr.mean()

25.0

In [160]:
arr.max()

49

In [161]:
np.square(arr)

array([   1,   25,   81,  169,  289,  441,  625,  841, 1089, 1369, 1681,
       2025, 2401])

In [164]:
np.lcm(34,21)

714

# Axis Logic

In [171]:
np.random.seed(91)
arr_new_2d = np.random.randint(1,20,(3,4))
arr_new_2d

#axis 0 : vertical axis (rows)
#axis 1 : horizontal axis (columns)

array([[19, 15, 11, 19],
       [15,  5,  6,  3],
       [11, 15, 18, 18]])

In [172]:
arr_new_2d.sum()

155

In [173]:
arr_new_2d.sum(axis=0)

array([45, 35, 35, 40])

In [174]:
arr_new_2d.sum(axis=1)

array([64, 29, 62])

In [175]:
arr_new_2d.var(axis=1)

array([11.    , 21.1875,  8.25  ])

In [176]:
arr_new_2d.std(axis=1)

array([3.31662479, 4.60298816, 2.87228132])